name: Update FRED Series Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'  # Run every twenty minutes

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run FRED series updates script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python FRED_series_updates.py

      - name: Commit and push if it changed
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add seriess_data.csv
          git commit -m "Update FRED series data" -a || echo "No changes to commit"
          git push
